version: '3'
services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "9000:9000"
    command: flask

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
